linters:
    disable-all: true
    enable:
      - bodyclose
      - copyloopvar
      - gosec
      - misspell
      - staticcheck

output:
  formats:
    - format: colored-line-number
    - format: json
      path: stderr
      
run:
  timeout: "5m"
  issues-exit-code: 1
