name: Code Linting

on: [push]

jobs:
  golintci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21.0'
      - uses: actions/checkout@v4
      - name: golintci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: -c .golangci.yaml
