name: Code Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21.0'
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - run: make lint
